version: '2'
services:
  bot:
    image: "amoniacou/slackopher:latest"
    ports:
     - "3030:3030"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  elasticsearch:
    image: "elasticsearch"
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    ports: ['127.0.0.1:9200:9200']
